### PR TITLE
Management command to deploy dashboard

### PR DESCRIPTION
**Pull request by oudeismetis**
fixes istrategylabs/franklin#95

This new management command provides a quick and easy way to deploy the default dashboard after the api and builder have been deployed.

### CODE REVIEW

**Comment by oudeismetis** [comment]
I had thought about both points and decided to be very "MVP" with this PR. I figured sooner or later we'll have it ask you additional questions about which dashboard you'd like to use. But before anyone could even do that, we need to resolve the deploy key issue in builder so that it can actually deploy sites like that.

This is a step 1.

As far as updates go, the webhook is still registered so any pushes to master will trigger a re-deploy.

**Comment by josephabrahams** [comment]
But how could external users register a webhook with an istrategylabs repo?

**Comment by oudeismetis** [comment]
This is a problem we've run into already. If you don't have permissions on the repo to do things like registering webhooks, franklin tells you that you don't have proper permissions and won't let you register the site.

o yes, with this PR, someone would have to fork the dashboard and change those values before using this management command. Or they'd skip the management command and do what we were doing before, which is call the API manually for the dashboard they want.

**Comment by oudeismetis** [comment]
We also still have the problem that dashboard isn't deployed to `dashboard.islstatic.com`. Probably something that could also be fixed in this management command as we'd have to opportunity here to tell API that "this is the special dashboard that you are configuring in your whitelist".

**Comment by josephabrahams** [comment]
I believe that this is outside of the scope of responsibilities for the API. With this implementation we've now tightly coupled the dashboard and API in a way that currently only works for a single user. 

I'd hate to say it, but perhaps a super simple Node.js backend that allows the dashboard to be deployed independently would remove all of the problems associated with franklin inception.

**Comment by oudeismetis** [comment]
Going to add a ticket to revisit this issue in January once we have the whole team back together.

**Pull request closed without merging**
